# Generated by Django 5.1.1 on 2024-11-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productentry_tokoentry_remove_business_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokoentry',
            old_name='location',
            new_name='category',
        ),
    ]
